// Tests the distribution generated by Java's Math.random() function.
public class TestRandom {
public static void main(String[] args) {
		
	int n = Integer.parseInt(args[0]);
	double big = 0;
	double small = 0;
	for (int i = 0; i < n ; i++){
	if (Math.random() > 0.5) {
			big++;
		}
		else {
			small++;
		}
	}
	double ratio;
	if (big > small) {
		ratio = (double)(small / big);
	} else {
		ratio = (double)(big / small);
	}
	System.out.println("> 0.5: " + big + " times");
	System.out.println("<= 0.5: " + small + " times");
	System.out.println("Ratio: " + ratio);


}
}
